
resources:
  - name: testing
    type: gitRepo
    repoPath: vijayreddy1991/testresources
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: testing
    steps:  
      - name: testJob1
        type: bash
        execution:
          onExecute:
            - echo "hello!"
  - name: testing
    steps:  
      - name: testJob2
        type: bash
        execution:
          onExecute:
            - echo "hello!"


            
