
resources:
  - name: testing
    type: gitRepo
    repoPath: vijayreddy1991/testresources
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipe1@




            
