
resources:
  - name: testing
    type: gitRepo
    repoPath: vijayreddy1991/testresources
    configuration:
      integrationName: github_vijay
      branches:
        only: master
    initialVersion:
      sha: master
      
  - name: webhookIntegrationResource
    type: webhook
    configuration:
      integrationName: incomingWebhookIntegration
    initialVersion:
      payload: vijay

pipelines:
  - name: testing
    steps:  
      - name: testJob1
        type: bash
        triggeredBy:
          resources:
            - webhookIntegrationResource
        execution:
          onExecute:
            - echo "hello!"


            
