
resources:
  - name: testing
    type: gitRepo
    repoPath: vijayreddy1991/testresources
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline
    steps:
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
              image:
                auto:
                  language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
             - node -v


            
