
resources:
  - name: testing1234
    type: gitRepo
    repoPath: vijayreddy1991/testresources
    configuration:
      integrationName: github_vijay_kumar
      branches:
        only: master
      tags:
#         except: <regular expression>
        only: master       
    version:
      sha: master
      
pipelines:
  - name: pipe_steps
    steps:
      - name: step_state
        type: bash
        setup:
          runtime:            
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - testing1234
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - echo "vijay"            




            
